# Generated by Django 4.1.5 on 2023-09-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_med_type_profile_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
