# Generated by Django 4.1.5 on 2023-05-31 15:28

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_rename_agent_type_profile_med_type_alter_profile_id_and_more'),
        ('conference', '0002_alter_timebreakdown_options_timebreakdown_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=500)),
                ('name_author', models.CharField(max_length=500)),
                ('corresponding_author', models.CharField(max_length=500)),
                ('corresponding_author_phone', models.CharField(max_length=25)),
                ('corresponding_author_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('background', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('objective', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('method', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('result', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('conclusion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('upload', models.FileField(upload_to='uploads/% Y/% m/% d/')),
                ('article_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('approved', models.BooleanField(default=False)),
                ('draft', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to='account.profile')),
                ('event', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='conference.event')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
            options={
                'verbose_name': 'Abstract',
                'verbose_name_plural': 'Abstract',
                'ordering': ['-created', '-updated'],
            },
        ),
    ]
