# Generated by Django 4.1.5 on 2023-08-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='upload',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
