# Generated by Django 4.1.5 on 2023-08-20 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_med_type_profile_membership_type'),
        ('conference', '0002_alter_timebreakdown_options_timebreakdown_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='ad_image',
            new_name='speaker_image',
        ),
        migrations.RenameField(
            model_name='timebreakdown',
            old_name='event',
            new_name='events',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='event',
        ),
        migrations.AddField(
            model_name='speaker',
            name='events',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='conference.event'),
        ),
        migrations.CreateModel(
            name='RegisterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prove_of_payment', models.ImageField(blank=True, default='profile/None/no_image.png', null=True, upload_to='img')),
                ('approved_payment', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=25, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('event_registered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.event')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
    ]
