# Generated by Django 4.1.5 on 2023-08-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='follow_up',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
