# Generated by Django 4.1.5 on 2023-08-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_event_follow_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
