# Generated by Django 4.1.5 on 2023-08-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_speaker_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
    ]
