# Generated by Django 4.1.5 on 2023-08-24 05:15

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='profile/None/no_image.png', null=True, upload_to=blog.models.upload_location),
        ),
    ]
